### ISSUE TITLE
Dhruv comments

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#1]
- The phrasing "..few amount of network incidents.." is a bit odd.
- There is a singular module defined in the I-D, but the abstract says plural "modules". 
- Recheck the reference at "L3VPN services related with the interface will become unavailable [I-D.ietf-ippm-pam]" or expand the text to correlate with the reference. 
- BCP14 template is repeated twice in Section 2
- Section 7, please regenerate the tree, as it does not match the YANG module. For instance there is no leaf called "csn"...
- Section 7.1 claims that there are two YANG modules "ietf-incident-type" and "ietf-incident" but the actual module in section 8 is a merged one.  
- Section 7.{4,5}, some text needs to be added on the asynchronous nature of these RPC and how the incident client would learn about the output of these rpcs?
- Section 8, update the WG details in the YANG module; the yang file formatting is off (use this command "pyang --ietf --lint -f yang --keep-comments --yang-line-length 69 " to fix that); 
- Is cross-domain == multi-layer (Section 3.3)? Think about making that clear.  Perhaps you should differentiate between inter-domain and inter-layer?
- Is cause-name some well known cause or just free form string? (same for incident's name)
- Please add a description for what are root-events and how it relates to root-cause 
- Section 9, security consideration is just the template, actual analysis is missing
- Section 10, please fix the formatting of the IANA registry
- Please run a grammar check tool
- Please add JSON or XML examples

**Comment by billwuqin** [comment]
Fixed.
