### ISSUE TITLE
incident-id vs incident-no

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#13]
https://github.com/ietf-wg-nmop/draft-ietf-nmop-network-incident-yang/blob/4c747144c025fc24bd4245ca0a4e1afa53ffbbf3/yang/ietf-incident.yang#L819C12-L819C22

What is the link between these two? Are these overlapping? If not, we need to explain what we have both. Thanks.

**Comment by billwuqin** [comment]
Clarify the relationship between incident-no and incident-id, incident-id is optional qualifier and can be empty string while incident no is sequence number or serial number which is mandatory to have. I have made changes to both tree diagram and YANG model source code to reflect this.
