### ISSUE TITLE
clarify incident management vs. fault management 

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#17]
See more context here: https://mailarchive.ietf.org/arch/msg/nmop/LXqGdhaf6gtOVjNReatEpI7yoT0/

**Comment by billwuqin** [comment]
See incident management definition update, which clarify the difference between fault management and incident management.
https://github.com/ietf-wg-nmop/draft-ietf-nmop-network-incident-yang/commit/6f7e76bb60771c72e91569b9aed4f0548000a9ea
