### ISSUE TITLE
Qiufang's comments

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#2]
•	Section 6.2, there are some RPCs defined that might change the status of an incident instance, I would suggest authors to consider adding a figure here to illustrate how each RPC operation would affect the incident status.
•	Section 7.1, the text related to the “ietf-incident-type” module should be removed as the draft doesn’t have it anymore;
•	Section 7.4 and 7.5, if the incident-diagnose and incident-resolve cannot be performed successfully (which I believe could be the very likely cases), an RPC error response should be returned with the error info. The draft is silent on this, maybe some errors could be defined to identify the reason why the servers fails to diagnose/resolve a particular incident instance.

**Comment by billwuqin** [comment]
Fixed in the latest commit.
