### ISSUE TITLE
resolve network incidents

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#8]
> management.  The YANG modules are meant to provide a standard way to
> report, diagnose, and resolve network incidents for the sake of
> network service health and root cause analysis.

I don't think YANG modules "resolve network incident" but feed that process

**Comment by billwuqin** [comment]
You are probably right, Some incidents can be Resolved automatically in the incident management server, but it 
should get instructions from the Customer/Incident management client. for some incidents which can not be resolved, it needs to escalate to report. In you words, feed the process.
Maybe I should reword as help resolve network incidents?
