### ISSUE TITLE
offload/sync with the terminology draft

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-network-incident-yang#9]
https://github.com/ietf-wg-nmop/draft-ietf-nmop-network-incident-yang/blob/4c252f9fa986da5656ffedd463531640ea9e8fe4/draft-ietf-nmop-network-incident-yang.md?plain=1#L207

Align with the terminology draft.

**Comment by billwuqin** [comment]
Fixed in the following two commits.
https://github.com/ietf-wg-nmop/draft-ietf-nmop-network-incident-yang/commit/df5c970037551cca52a6923ceb5ec2240ec8300b
https://github.com/ietf-wg-nmop/draft-ietf-nmop-network-incident-yang/commit/d7508db85859c3f5e5436ae351b0c6cdc365ac3a
